	public void Start()
	public void Awake()
		this.PCbloom = base.gameObject.GetComponent<Bloom>();
		this.PCdepthOfField = base.gameObject.GetComponent<DepthOfFieldScatter>();
		this.PCVignetting = base.gameObject.GetComponent<Vignetting>();
		this.PCScreenOverlay = base.gameObject.GetComponent<ScreenOverlay>();
	private DepthOfFieldScatter PCdepthOfField;
	private ScreenOverlay PCScreenOverlay;
	private Bloom PCbloom;
	private Vignetting PCVignetting;
